netflix/config/routes.rb
Rails.application.routes.draw do
  
  root 'picks#index'
  devise_for :users

  resources :users 
  resources :picks

end

netflix/app/models/pick.rb
class Pick < ActiveRecord::Base
	belongs_to :user
	validates :past, presence: true
end

netflix/app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :picks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

netflix/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

netflix/app/controllers/picks_controller.rb
class PicksController < ApplicationController
	before_action :authenticate_user!
	def index
		@picks = current_user.picks.all
	end

	def show
		@pick = Pick.find(params[:id])
	end

	def new
		@pick = Pick.new
	end

	def edit
		@pick = Pick.find(params[:id])
	end

	def create 
		movie = infor(pick_params)
		@pick = current_user.picks.new(movie)
		if @pick
			redirect_to picks_path
		else
			render :new
		end
	end

	def update
		movie = infor(pick_params)
		@pick = Pick.find(params[:id])
		if @pick.update(movie)
			redirect_to pick_path
		else
			render :edit
		end
	end

	private

		def pick_params
			params.require(:pick).permit(:past)
		end

		def infor title
			title=title[:past].split.join("%20")
			response = HTTParty.get("http://netflixroulette.net/api/api.php?title=#{title}").parsed_response
		end

end

netflix/app/helpers/application_helper.rb
module ApplicationHelper
end

netflix/app/helpers/picks_helper.rb
module PicksHelper
end

netflix/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Netflix</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

netflix/app/views/picks/_form.html.erb
 <% if @pick.errors.any? %>
 	<ul>
 		<% @pick.errors.full_messages.each do |err| %>
 			<li><%= err %></li>
 		<%end%>
 	</ul>
 <%end%>

 <%= form_for @pick do |f| %>
   <%= f.label :past, 'Movie Title' %>
   <%= f.text_field :past %>

   <%= f.submit %>
 <% end %>

netflix/app/views/picks/index.html.erb
<%= current_user.picks %>

<%= link_to "Add movie", new_pick_path%>

netflix/app/views/picks/new.html.erb
<%= render 'form' %>